Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
